import type { Exercise, MuscleGroup } from "@/types/exercise"

export const curatedExercises: Exercise[] = [
  {
    id: "push_up",
    name: "Push-Up",
    description: "A classic bodyweight exercise that targets the chest, shoulders, and triceps.",
    difficulty: 4,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Chest",
    secondaryMuscles: ["Shoulders", "Triceps", "Core"],
    executionTips: [
      "Keep your body in a straight line from head to heels.",
      "Lower until your chest nearly touches the floor.",
      "Keep elbows at a 45-degree angle to your body.",
    ],
    hasAnimation: true,
    animationFile: "/animations/exercise/push-up.json",
  },
  {
    id: "wide_push_up",
    name: "Wide Push-Up",
    description: "A push-up variation with hands wider than shoulder-width, emphasizing the chest.",
    difficulty: 4,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Chest",
    secondaryMuscles: ["Shoulders", "Triceps"],
    executionTips: [
      "Place hands wider than shoulder-width apart.",
      "Keep your body straight throughout the movement.",
      "Lower your chest towards the floor with control.",
    ],
    hasAnimation: true,
    animationFile: "/animations/exercise/wide-push-up.json",
  },
  {
    id: "diamond_push_up",
    name: "Diamond Push-Up",
    description: "A narrow push-up that targets the triceps and inner chest.",
    difficulty: 6,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Triceps",
    secondaryMuscles: ["Chest", "Shoulders"],
    executionTips: [
      "Form a diamond shape with your thumbs and index fingers.",
      "Keep elbows close to your body throughout.",
      "Lower your chest to your hands with control.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "incline_push_up",
    name: "Incline Push-Up",
    description: "An easier push-up variation with hands elevated on a bench or step.",
    difficulty: 3,
    category: "strength",
    equipment: ["bodyweight", "bench"],
    primaryMuscle: "Chest",
    secondaryMuscles: ["Shoulders", "Triceps"],
    executionTips: [
      "Place hands on an elevated surface like a bench.",
      "Keep your body straight throughout.",
      "Lower your chest towards the surface with control.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "decline_push_up",
    name: "Decline Push-Up",
    description: "A push-up with feet elevated, increasing upper chest and shoulder engagement.",
    difficulty: 6,
    category: "strength",
    equipment: ["bodyweight", "bench"],
    primaryMuscle: "Chest",
    secondaryMuscles: ["Shoulders", "Triceps"],
    executionTips: [
      "Place feet on an elevated surface behind you.",
      "Keep your body straight; don't sag at the hips.",
      "Lower your chest with control and push back up.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "squat",
    name: "Squat",
    description: "A fundamental lower body exercise targeting the quads, glutes, and hamstrings.",
    difficulty: 3,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Quadriceps",
    secondaryMuscles: ["Glutes", "Hamstrings", "Core"],
    executionTips: [
      "Keep your chest up and back straight.",
      "Lower your hips until your thighs are parallel to the floor.",
      "Keep your knees tracking over your toes.",
    ],
    hasAnimation: true,
    animationFile: "/animations/exercise/squat.json",
  },
  {
    id: "bodyweight_lunge",
    name: "Forward Lunge",
    description: "A unilateral leg exercise that builds balance and leg strength.",
    difficulty: 4,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Quadriceps",
    secondaryMuscles: ["Glutes", "Hamstrings", "Calves"],
    executionTips: [
      "Step forward with one leg and lower your hips.",
      "Keep your front knee aligned with your ankle.",
      "Push through your front heel to return to start.",
    ],
    hasAnimation: true,
    animationFile: "/animations/exercise/lunge.json",
  },
  {
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    description: "A challenging single-leg squat with rear foot elevated.",
    difficulty: 6,
    category: "strength",
    equipment: ["bodyweight", "bench"],
    primaryMuscle: "Quadriceps",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    executionTips: [
      "Place the top of your rear foot on a bench behind you.",
      "Lower your hips until your front thigh is parallel to the floor.",
      "Keep your torso upright throughout.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    description: "A hip extension exercise that targets the glutes and hamstrings.",
    difficulty: 2,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Glutes",
    secondaryMuscles: ["Hamstrings", "Lower Back"],
    executionTips: [
      "Lie on your back with knees bent and feet flat on the floor.",
      "Push through your heels to lift your hips toward the ceiling.",
      "Squeeze your glutes at the top of the movement.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "calf_raise",
    name: "Calf Raise",
    description: "A simple exercise that strengthens the calf muscles.",
    difficulty: 2,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Calves",
    secondaryMuscles: [],
    executionTips: [
      "Stand with feet hip-width apart.",
      "Push through the balls of your feet to lift your heels.",
      "Lower your heels slowly with control.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "plank",
    name: "Plank",
    description: "An isometric core exercise that strengthens the entire midsection.",
    difficulty: 3,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Core",
    secondaryMuscles: ["Shoulders", "Back"],
    executionTips: [
      "Keep your body in a straight line from head to heels.",
      "Engage your core by pulling your belly button toward your spine.",
      "Don't let your hips sag or pike up.",
    ],
    hasAnimation: true,
    animationFile: "/animations/exercise/plank.json",
  },
  {
    id: "crunch",
    name: "Crunch",
    description: "A classic abdominal exercise targeting the rectus abdominis.",
    difficulty: 2,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Rectus Abdominis",
    secondaryMuscles: ["Obliques"],
    executionTips: [
      "Lie on your back with knees bent and feet flat.",
      "Lift your shoulders off the floor using your abs.",
      "Avoid pulling on your neck with your hands.",
    ],
    hasAnimation: true,
    animationFile: "/animations/exercise/crunch.json",
  },
  {
    id: "bicycle_crunch",
    name: "Bicycle Crunch",
    description: "A dynamic core exercise that targets the rectus abdominis and obliques.",
    difficulty: 4,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Obliques",
    secondaryMuscles: ["Rectus Abdominis", "Hip Flexors"],
    executionTips: [
      "Lie on your back with hands behind your head.",
      "Bring your right elbow to your left knee while extending your right leg.",
      "Alternate sides in a pedaling motion.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "leg_raise",
    name: "Leg Raise",
    description: "A lower abdominal exercise performed by lifting the legs while lying on your back.",
    difficulty: 4,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Rectus Abdominis (Lower)",
    secondaryMuscles: ["Hip Flexors"],
    executionTips: [
      "Lie flat on your back with legs straight.",
      "Lift your legs to 90 degrees while keeping them straight.",
      "Lower your legs slowly without letting your back arch.",
    ],
    hasAnimation: true,
    animationFile: "/animations/exercise/leg-raise.json",
  },
  {
    id: "russian_twist",
    name: "Russian Twist",
    description: "A rotational core exercise that targets the obliques.",
    difficulty: 4,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Obliques",
    secondaryMuscles: ["Rectus Abdominis"],
    executionTips: [
      "Sit with knees bent and lean back slightly.",
      "Rotate your torso to one side, then the other.",
      "Keep your core engaged throughout.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "mountain_climber",
    name: "Mountain Climber",
    description: "A dynamic full-body exercise that elevates heart rate while building core and leg strength.",
    difficulty: 5,
    category: "cardio",
    equipment: ["bodyweight"],
    primaryMuscle: "Core",
    secondaryMuscles: ["Shoulders", "Hip Flexors", "Quadriceps"],
    executionTips: [
      "Start in a plank position.",
      "Drive one knee toward your chest, then quickly switch legs.",
      "Keep your hips low and core engaged.",
    ],
    hasAnimation: true,
    animationFile: "/animations/exercise/mountain-climber.json",
  },
  {
    id: "burpee",
    name: "Burpee",
    description: "A high-intensity full-body exercise combining a squat, push-up, and jump.",
    difficulty: 7,
    category: "cardio",
    equipment: ["bodyweight"],
    primaryMuscle: "Full Body",
    secondaryMuscles: ["Chest", "Quadriceps", "Core", "Shoulders"],
    executionTips: [
      "Start standing, then squat down and place hands on the floor.",
      "Kick your feet back into a push-up position.",
      "Jump your feet back in and explode up into a jump.",
    ],
    hasAnimation: true,
    animationFile: "/animations/exercise/burpee.json",
  },
  {
    id: "jumping_jack",
    name: "Jumping Jack",
    description: "A classic full-body cardio exercise that gets your heart rate up.",
    difficulty: 2,
    category: "cardio",
    equipment: ["bodyweight"],
    primaryMuscle: "Cardio",
    secondaryMuscles: ["Shoulders", "Calves", "Hip Abductors"],
    executionTips: [
      "Start with feet together and arms at your sides.",
      "Jump while spreading your legs and raising your arms overhead.",
      "Return to the starting position and repeat.",
    ],
    hasAnimation: true,
    animationFile: "/animations/exercise/jumping-jack.json",
  },
  {
    id: "high_knees",
    name: "High Knees",
    description: "A high-intensity cardio exercise that involves running in place with exaggerated knee lift.",
    difficulty: 5,
    category: "cardio",
    equipment: ["bodyweight"],
    primaryMuscle: "Cardio",
    secondaryMuscles: ["Hip Flexors", "Quadriceps", "Core"],
    executionTips: [
      "Stand tall and drive one knee up toward your chest.",
      "Quickly switch legs in a running motion.",
      "Pump your arms for momentum.",
    ],
    hasAnimation: true,
    animationFile: "/animations/exercise/high-knees.json",
  },
  {
    id: "pull_up",
    name: "Pull-Up",
    description: "An upper body pulling exercise that targets the back and biceps.",
    difficulty: 8,
    category: "strength",
    equipment: ["bodyweight", "pull-up bar"],
    primaryMuscle: "Latissimus Dorsi",
    secondaryMuscles: ["Biceps", "Rhomboids", "Rear Deltoids"],
    executionTips: [
      "Hang from the bar with an overhand grip slightly wider than shoulder-width.",
      "Pull yourself up until your chin clears the bar.",
      "Lower yourself with control to full extension.",
    ],
    hasAnimation: true,
    animationFile: "/animations/exercise/pull-up.json",
  },
  {
    id: "superman",
    name: "Superman Hold",
    description: "A back extension exercise that strengthens the lower back and glutes.",
    difficulty: 2,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Erector Spinae",
    secondaryMuscles: ["Glutes", "Shoulders"],
    executionTips: [
      "Lie face down with arms extended overhead.",
      "Lift your arms, chest, and legs off the floor simultaneously.",
      "Hold at the top and squeeze your lower back.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "dip",
    name: "Dip",
    description: "A compound upper body exercise targeting the triceps, chest, and shoulders.",
    difficulty: 7,
    category: "strength",
    equipment: ["bodyweight", "parallel bars"],
    primaryMuscle: "Triceps",
    secondaryMuscles: ["Chest", "Shoulders"],
    executionTips: [
      "Grip the bars and lift yourself up with arms extended.",
      "Lower your body by bending your elbows to 90 degrees.",
      "Push yourself back up to the starting position.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "triceps_dip_bench",
    name: "Bench Triceps Dip",
    description: "A triceps exercise using a bench or chair for support.",
    difficulty: 4,
    category: "strength",
    equipment: ["bodyweight", "bench"],
    primaryMuscle: "Triceps",
    secondaryMuscles: ["Chest", "Shoulders"],
    executionTips: [
      "Place hands on the edge of a bench behind you.",
      "Lower your body by bending your elbows to 90 degrees.",
      "Push through your palms to return to start.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "wall_sit",
    name: "Wall Sit",
    description: "An isometric exercise that targets the quadriceps and glutes.",
    difficulty: 4,
    category: "strength",
    equipment: ["bodyweight"],
    primaryMuscle: "Quadriceps",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    executionTips: [
      "Lean against a wall and slide down until thighs are parallel to the floor.",
      "Keep your back flat against the wall.",
      "Hold the position for time.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "downward_dog",
    name: "Downward Dog",
    description: "A yoga pose that stretches and strengthens the entire body.",
    difficulty: 2,
    category: "stretching",
    equipment: ["bodyweight"],
    primaryMuscle: "Back",
    secondaryMuscles: ["Shoulders", "Hamstrings", "Calves"],
    executionTips: [
      "Start on hands and knees, then lift your hips toward the ceiling.",
      "Press your heels toward the floor.",
      "Keep your head between your arms and relax your neck.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "cat_cow",
    name: "Cat-Cow Stretch",
    description: "A gentle spinal mobility exercise alternating between arching and rounding the back.",
    difficulty: 1,
    category: "stretching",
    equipment: ["bodyweight"],
    primaryMuscle: "Back",
    secondaryMuscles: ["Core"],
    executionTips: [
      "Start on hands and knees with a neutral spine.",
      "Inhale and drop your belly, lifting your head and tailbone (Cow).",
      "Exhale and round your spine, tucking your chin (Cat).",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "childs_pose",
    name: "Child's Pose",
    description: "A resting yoga pose that gently stretches the back, hips, and thighs.",
    difficulty: 1,
    category: "stretching",
    equipment: ["bodyweight"],
    primaryMuscle: "Back",
    secondaryMuscles: ["Hips"],
    executionTips: [
      "Kneel on the floor with toes together and knees apart.",
      "Sit back on your heels and extend your arms forward.",
      "Rest your forehead on the floor and breathe deeply.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
  {
    id: "standing_toe_touch",
    name: "Standing Toe Touch",
    description: "A hamstring stretch that improves lower body flexibility.",
    difficulty: 2,
    category: "stretching",
    equipment: ["bodyweight"],
    primaryMuscle: "Hamstrings",
    secondaryMuscles: ["Lower Back", "Calves"],
    executionTips: [
      "Stand with feet hip-width apart and legs straight.",
      "Hinge at the hips and reach toward your toes.",
      "Bend only as far as comfortable and hold.",
    ],
    hasAnimation: false,
    animationFile: null,
  },
]

export const muscleGroups: { id: MuscleGroup; label: string }[] = [
  { id: "chest", label: "Chest" },
  { id: "back", label: "Back" },
  { id: "shoulders", label: "Shoulders" },
  { id: "biceps", label: "Biceps" },
  { id: "triceps", label: "Triceps" },
  { id: "forearms", label: "Forearms" },
  { id: "abs", label: "Abs" },
  { id: "obliques", label: "Obliques" },
  { id: "quadriceps", label: "Quadriceps" },
  { id: "hamstrings", label: "Hamstrings" },
  { id: "glutes", label: "Glutes" },
  { id: "calves", label: "Calves" },
  { id: "cardio", label: "Cardio" },
  { id: "full_body", label: "Full Body" },
  { id: "core", label: "Core" },
  { id: "other", label: "Other" },
]

export function getExerciseById(id: string): Exercise | undefined {
  return curatedExercises.find((ex) => ex.id === id)
}

export function getExercisesByMuscle(muscle: string): Exercise[] {
  const lower = muscle.toLowerCase()
  return curatedExercises.filter(
    (ex) =>
      ex.primaryMuscle.toLowerCase() === lower ||
      ex.secondaryMuscles.some((m) => m.toLowerCase() === lower),
  )
}

export function getExercisesByCategory(category: string): Exercise[] {
  return curatedExercises.filter((ex) => ex.category === category)
}

export function getExercisesByEquipment(equipment: string): Exercise[] {
  return curatedExercises.filter((ex) =>
    ex.equipment.some((e) => e.toLowerCase() === equipment.toLowerCase()),
  )
}

export function searchExercises(query: string): Exercise[] {
  const lower = query.toLowerCase()
  return curatedExercises.filter(
    (ex) =>
      ex.name.toLowerCase().includes(lower) ||
      ex.primaryMuscle.toLowerCase().includes(lower) ||
      ex.secondaryMuscles.some((m) => m.toLowerCase().includes(lower)) ||
      ex.description.toLowerCase().includes(lower),
  )
}

export function getExercisesWithAnimation(): Exercise[] {
  return curatedExercises.filter((ex) => ex.hasAnimation)
}
